# openagent/ui/export_templates.py
"""
Branded export builders for the OpenAgent web UI.

Turns a chat response (markdown-ish text) into a styled PDF / DOCX / TXT
download with an OpenAgent header, accent colors, and light markdown
rendering (headings, bullets, code fences, **bold**, `inline code`).

Kept free of Flask/agent imports so it can be unit-tested standalone.
The PDF path embeds NotoSansKannada so non-Latin text (Kannada/Hindi
etc.) renders instead of empty boxes — same i18n guarantee as before.
"""

from __future__ import annotations

import io
import logging
import re
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("openagent.ui.export")

# ── Brand palette ───────────────────────────────────────────────
_PURPLE = "#7C3AED"
_CYAN = "#06B6D4"
_DARK = "#0F172A"
_GREY = "#6B7280"
_CODE_BG = "#F1F5F9"
_CODE_BORDER = "#CBD5E1"

_FONT_PATH = Path(__file__).resolve().parent / "fonts" / "NotoSansKannada.ttf"

_BOLD_RE = re.compile(r"\*\*([^*]+)\*\*")
_INLINE_CODE_RE = re.compile(r"`([^`]+)`")


# ── Markdown-lite block parser (shared by PDF and DOCX) ─────────
def _parse_blocks(text: str) -> list[tuple[str, object]]:
    """
    Split response text into (kind, content) blocks.
    Kinds: 'h1'/'h2'/'h3' (str), 'bullet' (str), 'number' (str),
    'code' (list[str]), 'para' (str), 'blank' (None).
    """
    blocks: list[tuple[str, object]] = []
    code_lines: list[str] | None = None

    for line in text.split("\n"):
        stripped = line.strip()

        if stripped.startswith("```"):
            if code_lines is None:
                code_lines = []
            else:
                blocks.append(("code", code_lines))
                code_lines = None
            continue
        if code_lines is not None:
            code_lines.append(line.rstrip())
            continue

        if not stripped:
            blocks.append(("blank", None))
        elif stripped.startswith("### "):
            blocks.append(("h3", stripped[4:]))
        elif stripped.startswith("## "):
            blocks.append(("h2", stripped[3:]))
        elif stripped.startswith("# "):
            blocks.append(("h1", stripped[2:]))
        elif stripped[:2] in ("- ", "* ", "• "):
            blocks.append(("bullet", stripped[2:]))
        elif re.match(r"^\d+[.)]\s+", stripped):
            blocks.append(("number", re.sub(r"^\d+[.)]\s+", "", stripped)))
        else:
            blocks.append(("para", stripped))

    if code_lines is not None:  # unterminated fence — flush as code
        blocks.append(("code", code_lines))
    return blocks


def _timestamp() -> str:
    return datetime.now().strftime("%d %b %Y, %H:%M")


# ── TXT ─────────────────────────────────────────────────────────
def build_txt(text: str) -> bytes:
    banner = (
        "════════════════════════════════════════\n"
        "  OPENAGENT — Response Export\n"
        f"  Generated: {_timestamp()}\n"
        "════════════════════════════════════════\n\n"
    )
    return (banner + text + "\n").encode("utf-8")


# ── PDF ─────────────────────────────────────────────────────────
def _xml_escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _pdf_inline(s: str) -> str:
    """Escaped text → reportlab inline markup for **bold** and `code`."""
    s = _xml_escape(s)
    s = _BOLD_RE.sub(r"<b>\1</b>", s)
    s = _INLINE_CODE_RE.sub(r'<font face="Courier" color="#0E7490">\1</font>', s)
    return s


def _pdf_page_decor(canvas, doc) -> None:
    """Header band + footer drawn on every page."""
    from reportlab.lib.colors import HexColor
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.units import inch

    w, h = letter
    canvas.saveState()
    # Dark header band with wordmark and purple accent line
    canvas.setFillColor(HexColor(_DARK))
    canvas.rect(0, h - 0.9 * inch, w, 0.9 * inch, fill=1, stroke=0)
    canvas.setFillColor(HexColor(_CYAN))
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(0.75 * inch, h - 0.55 * inch, "OPENAGENT")
    canvas.setFillColor(HexColor("#94A3B8"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(0.75 * inch, h - 0.72 * inch,
                      "Hybrid AI Assistant  •  Response Export")
    canvas.setFillColor(HexColor(_PURPLE))
    canvas.rect(0, h - 0.96 * inch, w, 0.06 * inch, fill=1, stroke=0)
    # Footer rule, credit and page number
    canvas.setStrokeColor(HexColor(_PURPLE))
    canvas.setLineWidth(0.8)
    canvas.line(0.75 * inch, 0.62 * inch, w - 0.75 * inch, 0.62 * inch)
    canvas.setFillColor(HexColor(_GREY))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(0.75 * inch, 0.45 * inch, f"Generated by OpenAgent  •  {_timestamp()}")
    canvas.drawRightString(w - 0.75 * inch, 0.45 * inch, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


def build_pdf(text: str) -> bytes:
    from reportlab.lib.colors import HexColor
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (HRFlowable, Paragraph, SimpleDocTemplate,
                                    Spacer)

    # Unicode font (Latin + Kannada). Map every family variant to the same
    # face so <b>/<i> markup never crashes on a missing bold variant.
    base_font = "Helvetica"
    try:
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont

        if "NotoKannada" not in pdfmetrics.getRegisteredFontNames():
            pdfmetrics.registerFont(TTFont("NotoKannada", str(_FONT_PATH)))
            pdfmetrics.registerFontFamily(
                "NotoKannada", normal="NotoKannada", bold="NotoKannada",
                italic="NotoKannada", boldItalic="NotoKannada")
        base_font = "NotoKannada"
    except Exception:
        logger.warning("Noto font unavailable — PDF export falls back to Latin-only")

    styles = getSampleStyleSheet()
    body = ParagraphStyle("OABody", parent=styles["Normal"], fontName=base_font,
                          fontSize=10.5, leading=15, textColor=HexColor("#1F2937"))
    title = ParagraphStyle("OATitle", parent=styles["Title"], fontName=base_font,
                           fontSize=20, textColor=HexColor(_DARK), spaceAfter=2)
    meta = ParagraphStyle("OAMeta", parent=body, fontSize=8.5,
                          textColor=HexColor(_GREY))
    heads = {
        "h1": ParagraphStyle("OAH1", parent=body, fontSize=15, leading=19,
                             textColor=HexColor(_PURPLE), spaceBefore=10, spaceAfter=4),
        "h2": ParagraphStyle("OAH2", parent=body, fontSize=13, leading=17,
                             textColor=HexColor(_PURPLE), spaceBefore=8, spaceAfter=3),
        "h3": ParagraphStyle("OAH3", parent=body, fontSize=11.5, leading=15,
                             textColor=HexColor("#0E7490"), spaceBefore=6, spaceAfter=2),
    }
    bullet = ParagraphStyle("OABullet", parent=body, leftIndent=16, bulletIndent=6)
    code = ParagraphStyle("OACode", parent=styles["Code"], fontName="Courier",
                          fontSize=8.5, leading=11.5, backColor=HexColor(_CODE_BG),
                          borderColor=HexColor(_CODE_BORDER), borderWidth=0.5,
                          borderPadding=6, textColor=HexColor(_DARK),
                          spaceBefore=4, spaceAfter=4)

    story = [
        Paragraph("OpenAgent Response", title),
        Paragraph(f"Exported {_timestamp()}", meta),
        Spacer(1, 0.08 * inch),
        HRFlowable(width="100%", thickness=1.2, color=HexColor(_CYAN)),
        Spacer(1, 0.16 * inch),
    ]

    for kind, content in _parse_blocks(text):
        if kind == "blank":
            story.append(Spacer(1, 0.09 * inch))
        elif kind in heads:
            story.append(Paragraph(_pdf_inline(str(content)), heads[kind]))
        elif kind == "bullet":
            story.append(Paragraph(_pdf_inline(str(content)), bullet, bulletText="•"))
        elif kind == "number":
            story.append(Paragraph(_pdf_inline(str(content)), bullet, bulletText="–"))
        elif kind == "code":
            joined = "<br/>".join(_xml_escape(ln) or " " for ln in content)
            story.append(Paragraph(joined or " ", code))
        else:
            story.append(Paragraph(_pdf_inline(str(content)), body))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=1.25 * inch,
                            bottomMargin=0.95 * inch, leftMargin=0.75 * inch,
                            rightMargin=0.75 * inch, title="OpenAgent Response")
    doc.build(story, onFirstPage=_pdf_page_decor, onLaterPages=_pdf_page_decor)
    return buf.getvalue()


# ── DOCX ────────────────────────────────────────────────────────
def _docx_inline_runs(paragraph, text: str, mono_font: str = "Courier New") -> None:
    """Add runs to a python-docx paragraph, honoring **bold** and `code`."""
    from docx.shared import RGBColor

    pos = 0
    for m in re.finditer(r"\*\*([^*]+)\*\*|`([^`]+)`", text):
        if m.start() > pos:
            paragraph.add_run(text[pos:m.start()])
        if m.group(1) is not None:
            paragraph.add_run(m.group(1)).bold = True
        else:
            run = paragraph.add_run(m.group(2))
            run.font.name = mono_font
            run.font.color.rgb = RGBColor(0x0E, 0x74, 0x90)
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


def _docx_bottom_border(paragraph, color_hex: str = "06B6D4") -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    p_pr = paragraph._p.get_or_add_pPr()
    borders = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "12")
    bottom.set(qn("w:color"), color_hex)
    borders.append(bottom)
    p_pr.append(borders)


def build_docx(text: str) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor

    purple = RGBColor(0x7C, 0x3A, 0xED)
    cyan = RGBColor(0x06, 0xB6, 0xD4)
    grey = RGBColor(0x6B, 0x72, 0x80)
    dark = RGBColor(0x0F, 0x17, 0x2A)

    doc = Document()

    mark = doc.add_paragraph()
    run = mark.add_run("OPENAGENT")
    run.bold = True
    run.font.size = Pt(11)
    run.font.color.rgb = cyan

    title = doc.add_paragraph()
    run = title.add_run("OpenAgent Response")
    run.bold = True
    run.font.size = Pt(22)
    run.font.color.rgb = dark

    meta = doc.add_paragraph()
    run = meta.add_run(f"Hybrid AI Assistant  •  Exported {_timestamp()}")
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = grey
    _docx_bottom_border(meta)

    for kind, content in _parse_blocks(text):
        if kind == "blank":
            continue
        if kind in ("h1", "h2", "h3"):
            level = {"h1": 1, "h2": 2, "h3": 3}[kind]
            heading = doc.add_heading("", level=level)
            _docx_inline_runs(heading, str(content))
            for h_run in heading.runs:
                h_run.font.color.rgb = purple if level < 3 else RGBColor(0x0E, 0x74, 0x90)
        elif kind in ("bullet", "number"):
            style = "List Bullet" if kind == "bullet" else "List Number"
            try:
                para = doc.add_paragraph(style=style)
            except KeyError:
                para = doc.add_paragraph()
                para.add_run("•  " if kind == "bullet" else "–  ")
            _docx_inline_runs(para, str(content))
        elif kind == "code":
            for line in content or [""]:
                para = doc.add_paragraph()
                run = para.add_run(line if line else " ")
                run.font.name = "Courier New"
                run.font.size = Pt(9)
                run.font.color.rgb = dark
                para.paragraph_format.space_after = Pt(0)
        else:
            para = doc.add_paragraph()
            _docx_inline_runs(para, str(content))

    footer = doc.sections[0].footer.paragraphs[0]
    run = footer.add_run(f"Generated by OpenAgent  •  {_timestamp()}")
    run.font.size = Pt(8)
    run.font.color.rgb = grey

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
